# Generated by Django 2.2.28 on 2026-03-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RateYourModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='message',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
